//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Settings/Control Schemes/Mech_Controller.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Mech_Controller : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Mech_Controller()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Mech_Controller"",
    ""maps"": [
        {
            ""name"": ""MechPilot"",
            ""id"": ""fe3a3948-7818-4a04-b434-88cd93b71bb7"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""9cc7a52d-b185-4ff9-b301-555773088682"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Fire1"",
                    ""type"": ""Button"",
                    ""id"": ""62e951fd-2e4f-4ea9-a013-d185daf9d96d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""8802992a-152f-473c-b31c-e89182209155"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Fire2"",
                    ""type"": ""Button"",
                    ""id"": ""a3858add-b64b-41ab-8c26-0860c22ef78d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeWeapon"",
                    ""type"": ""Button"",
                    ""id"": ""f195206d-67de-4019-83f7-c0ed6de54023"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WSAD"",
                    ""id"": ""a20065fc-8983-43c8-88a0-f6436c21432d"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""4433e0f7-2d6f-424d-8d68-67408a5a019b"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""7b787468-527f-4f02-aff5-90f5cbdb6943"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""dd4b7851-c7d3-49e1-805b-c39ffb194e1e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""18ef1f3b-e446-4b47-ae7b-8d1d4703aaa1"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c2de82e5-2e43-4e4d-bf8f-c7829d457d6b"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxController"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""NumpadMove"",
                    ""id"": ""9740a263-1357-4452-bf51-4424fe35e031"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""99e91d91-3e28-49b2-bba6-e5ba2903fbb3"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Fire1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c2e73f4-5905-4e90-bd66-5beb48b8c001"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxController"",
                    ""action"": ""Fire1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f1a62d32-1fe1-47f1-a7f8-241463c952f9"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0a6a7afd-4d30-407e-8428-6b567b416148"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxController"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9ba45e11-66f5-4262-8b10-45ff5d5bdd92"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Fire2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0adf44b5-f525-49ac-90d8-4db05bf3baa2"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxController"",
                    ""action"": ""Fire2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""de6ef2cc-4bdb-4f12-a1cc-625e4d0e05ff"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""ChangeWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""47df3803-ee56-4a4b-938c-364f0b30fee6"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxController"",
                    ""action"": ""ChangeWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""ElectronicWarfareOfficer"",
            ""id"": ""e0646344-bfa8-42c0-94c9-03ea77a5ae43"",
            ""actions"": [
                {
                    ""name"": ""IncreaseMinimapResolution"",
                    ""type"": ""Button"",
                    ""id"": ""3f024827-c976-4bf9-993b-316123425579"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DecreaseMinimapResolution"",
                    ""type"": ""Button"",
                    ""id"": ""7d695515-08ba-48c6-92a0-a10f25d84bd1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PointClick1"",
                    ""type"": ""Button"",
                    ""id"": ""562d5dab-5958-413e-9e46-09a8a21970cf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PointClick2"",
                    ""type"": ""Button"",
                    ""id"": ""16bf1c09-3464-4549-a25b-d1929678e337"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RadarSwitchPower"",
                    ""type"": ""Button"",
                    ""id"": ""31cf5ab1-c970-47b0-8fab-1826703d48df"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TerrainMapSwitch"",
                    ""type"": ""Button"",
                    ""id"": ""542f3196-88d5-4451-8571-e0002d1b5e4f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""IncreaseSweepSpeed"",
                    ""type"": ""Button"",
                    ""id"": ""7645a161-244e-4328-a9dd-4f6b25fd8a25"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DecreaseSweepSpeed"",
                    ""type"": ""Button"",
                    ""id"": ""9f4cdec1-26f1-47c6-a65a-13c3594191b4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleSectorSweep"",
                    ""type"": ""Button"",
                    ""id"": ""b2d7bda2-ec4e-4e6e-9468-7d26b0fc01ff"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""IncreaseSectorSweep"",
                    ""type"": ""Button"",
                    ""id"": ""6814ce42-fe5e-44fe-977b-2ad14c57bf31"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DecreaseSectorSweep"",
                    ""type"": ""Button"",
                    ""id"": ""3bfb8558-28f7-4bff-aff2-50ba01d587ba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateSectorSweepForward"",
                    ""type"": ""Button"",
                    ""id"": ""6e03d651-f1dc-49a7-9317-e8aa6ed55c0c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateSectorSweepBackward"",
                    ""type"": ""Button"",
                    ""id"": ""4ecf7e07-9683-4db6-be9b-b5223725aa84"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""JammTarget"",
                    ""type"": ""Button"",
                    ""id"": ""9519a42f-4172-4ce2-8026-1685c0890c2d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f4c010d4-e93f-4f93-ba6f-5942977ff848"",
                    ""path"": ""<Keyboard>/period"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""IncreaseMinimapResolution"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a7433f76-152f-4774-888c-b303fbfdef07"",
                    ""path"": ""<Keyboard>/comma"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""DecreaseMinimapResolution"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e44081c2-2396-4a6c-8988-926763814ca4"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""PointClick1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""47a23a39-955a-4741-aeea-ba6af885345b"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""RadarSwitchPower"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eb255fca-bd70-458c-85f9-fc520d3fe62a"",
                    ""path"": ""<Keyboard>/numpad2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""TerrainMapSwitch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""048a4379-bfc1-4bee-b911-f51185a9e1b1"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""PointClick2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""21e506ee-4177-48a7-9db2-4453b532b119"",
                    ""path"": ""<Keyboard>/numpadPlus"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""IncreaseSweepSpeed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d090a7eb-f03b-4083-9e04-4c4770fd5112"",
                    ""path"": ""<Keyboard>/numpadMinus"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DecreaseSweepSpeed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""875f58cc-ab19-41ba-864f-9c8aa9073421"",
                    ""path"": ""<Keyboard>/numpad3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""ToggleSectorSweep"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a1e6314-d528-4617-b55d-5ea00a4f6af3"",
                    ""path"": ""<Keyboard>/numpad4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""IncreaseSectorSweep"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6058c3ae-4c24-4b98-84cf-408fbba1b89e"",
                    ""path"": ""<Keyboard>/numpad5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""DecreaseSectorSweep"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""26c82476-c18f-46f8-94fc-de58c32d9c4a"",
                    ""path"": ""<Keyboard>/numpad6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""RotateSectorSweepForward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""82eb2395-77ce-4838-8b10-428596799054"",
                    ""path"": ""<Keyboard>/numpad7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""RotateSectorSweepBackward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""53deed56-74db-4d16-acff-cd0a95623066"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""JammTarget"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard&Mouse"",
            ""bindingGroup"": ""Keyboard&Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""XboxController"",
            ""bindingGroup"": ""XboxController"",
            ""devices"": [
                {
                    ""devicePath"": ""<XInputController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // MechPilot
        m_MechPilot = asset.FindActionMap("MechPilot", throwIfNotFound: true);
        m_MechPilot_Move = m_MechPilot.FindAction("Move", throwIfNotFound: true);
        m_MechPilot_Fire1 = m_MechPilot.FindAction("Fire1", throwIfNotFound: true);
        m_MechPilot_Look = m_MechPilot.FindAction("Look", throwIfNotFound: true);
        m_MechPilot_Fire2 = m_MechPilot.FindAction("Fire2", throwIfNotFound: true);
        m_MechPilot_ChangeWeapon = m_MechPilot.FindAction("ChangeWeapon", throwIfNotFound: true);
        // ElectronicWarfareOfficer
        m_ElectronicWarfareOfficer = asset.FindActionMap("ElectronicWarfareOfficer", throwIfNotFound: true);
        m_ElectronicWarfareOfficer_IncreaseMinimapResolution = m_ElectronicWarfareOfficer.FindAction("IncreaseMinimapResolution", throwIfNotFound: true);
        m_ElectronicWarfareOfficer_DecreaseMinimapResolution = m_ElectronicWarfareOfficer.FindAction("DecreaseMinimapResolution", throwIfNotFound: true);
        m_ElectronicWarfareOfficer_PointClick1 = m_ElectronicWarfareOfficer.FindAction("PointClick1", throwIfNotFound: true);
        m_ElectronicWarfareOfficer_PointClick2 = m_ElectronicWarfareOfficer.FindAction("PointClick2", throwIfNotFound: true);
        m_ElectronicWarfareOfficer_RadarSwitchPower = m_ElectronicWarfareOfficer.FindAction("RadarSwitchPower", throwIfNotFound: true);
        m_ElectronicWarfareOfficer_TerrainMapSwitch = m_ElectronicWarfareOfficer.FindAction("TerrainMapSwitch", throwIfNotFound: true);
        m_ElectronicWarfareOfficer_IncreaseSweepSpeed = m_ElectronicWarfareOfficer.FindAction("IncreaseSweepSpeed", throwIfNotFound: true);
        m_ElectronicWarfareOfficer_DecreaseSweepSpeed = m_ElectronicWarfareOfficer.FindAction("DecreaseSweepSpeed", throwIfNotFound: true);
        m_ElectronicWarfareOfficer_ToggleSectorSweep = m_ElectronicWarfareOfficer.FindAction("ToggleSectorSweep", throwIfNotFound: true);
        m_ElectronicWarfareOfficer_IncreaseSectorSweep = m_ElectronicWarfareOfficer.FindAction("IncreaseSectorSweep", throwIfNotFound: true);
        m_ElectronicWarfareOfficer_DecreaseSectorSweep = m_ElectronicWarfareOfficer.FindAction("DecreaseSectorSweep", throwIfNotFound: true);
        m_ElectronicWarfareOfficer_RotateSectorSweepForward = m_ElectronicWarfareOfficer.FindAction("RotateSectorSweepForward", throwIfNotFound: true);
        m_ElectronicWarfareOfficer_RotateSectorSweepBackward = m_ElectronicWarfareOfficer.FindAction("RotateSectorSweepBackward", throwIfNotFound: true);
        m_ElectronicWarfareOfficer_JammTarget = m_ElectronicWarfareOfficer.FindAction("JammTarget", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MechPilot
    private readonly InputActionMap m_MechPilot;
    private IMechPilotActions m_MechPilotActionsCallbackInterface;
    private readonly InputAction m_MechPilot_Move;
    private readonly InputAction m_MechPilot_Fire1;
    private readonly InputAction m_MechPilot_Look;
    private readonly InputAction m_MechPilot_Fire2;
    private readonly InputAction m_MechPilot_ChangeWeapon;
    public struct MechPilotActions
    {
        private @Mech_Controller m_Wrapper;
        public MechPilotActions(@Mech_Controller wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_MechPilot_Move;
        public InputAction @Fire1 => m_Wrapper.m_MechPilot_Fire1;
        public InputAction @Look => m_Wrapper.m_MechPilot_Look;
        public InputAction @Fire2 => m_Wrapper.m_MechPilot_Fire2;
        public InputAction @ChangeWeapon => m_Wrapper.m_MechPilot_ChangeWeapon;
        public InputActionMap Get() { return m_Wrapper.m_MechPilot; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MechPilotActions set) { return set.Get(); }
        public void SetCallbacks(IMechPilotActions instance)
        {
            if (m_Wrapper.m_MechPilotActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_MechPilotActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_MechPilotActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_MechPilotActionsCallbackInterface.OnMove;
                @Fire1.started -= m_Wrapper.m_MechPilotActionsCallbackInterface.OnFire1;
                @Fire1.performed -= m_Wrapper.m_MechPilotActionsCallbackInterface.OnFire1;
                @Fire1.canceled -= m_Wrapper.m_MechPilotActionsCallbackInterface.OnFire1;
                @Look.started -= m_Wrapper.m_MechPilotActionsCallbackInterface.OnLook;
                @Look.performed -= m_Wrapper.m_MechPilotActionsCallbackInterface.OnLook;
                @Look.canceled -= m_Wrapper.m_MechPilotActionsCallbackInterface.OnLook;
                @Fire2.started -= m_Wrapper.m_MechPilotActionsCallbackInterface.OnFire2;
                @Fire2.performed -= m_Wrapper.m_MechPilotActionsCallbackInterface.OnFire2;
                @Fire2.canceled -= m_Wrapper.m_MechPilotActionsCallbackInterface.OnFire2;
                @ChangeWeapon.started -= m_Wrapper.m_MechPilotActionsCallbackInterface.OnChangeWeapon;
                @ChangeWeapon.performed -= m_Wrapper.m_MechPilotActionsCallbackInterface.OnChangeWeapon;
                @ChangeWeapon.canceled -= m_Wrapper.m_MechPilotActionsCallbackInterface.OnChangeWeapon;
            }
            m_Wrapper.m_MechPilotActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Fire1.started += instance.OnFire1;
                @Fire1.performed += instance.OnFire1;
                @Fire1.canceled += instance.OnFire1;
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @Fire2.started += instance.OnFire2;
                @Fire2.performed += instance.OnFire2;
                @Fire2.canceled += instance.OnFire2;
                @ChangeWeapon.started += instance.OnChangeWeapon;
                @ChangeWeapon.performed += instance.OnChangeWeapon;
                @ChangeWeapon.canceled += instance.OnChangeWeapon;
            }
        }
    }
    public MechPilotActions @MechPilot => new MechPilotActions(this);

    // ElectronicWarfareOfficer
    private readonly InputActionMap m_ElectronicWarfareOfficer;
    private IElectronicWarfareOfficerActions m_ElectronicWarfareOfficerActionsCallbackInterface;
    private readonly InputAction m_ElectronicWarfareOfficer_IncreaseMinimapResolution;
    private readonly InputAction m_ElectronicWarfareOfficer_DecreaseMinimapResolution;
    private readonly InputAction m_ElectronicWarfareOfficer_PointClick1;
    private readonly InputAction m_ElectronicWarfareOfficer_PointClick2;
    private readonly InputAction m_ElectronicWarfareOfficer_RadarSwitchPower;
    private readonly InputAction m_ElectronicWarfareOfficer_TerrainMapSwitch;
    private readonly InputAction m_ElectronicWarfareOfficer_IncreaseSweepSpeed;
    private readonly InputAction m_ElectronicWarfareOfficer_DecreaseSweepSpeed;
    private readonly InputAction m_ElectronicWarfareOfficer_ToggleSectorSweep;
    private readonly InputAction m_ElectronicWarfareOfficer_IncreaseSectorSweep;
    private readonly InputAction m_ElectronicWarfareOfficer_DecreaseSectorSweep;
    private readonly InputAction m_ElectronicWarfareOfficer_RotateSectorSweepForward;
    private readonly InputAction m_ElectronicWarfareOfficer_RotateSectorSweepBackward;
    private readonly InputAction m_ElectronicWarfareOfficer_JammTarget;
    public struct ElectronicWarfareOfficerActions
    {
        private @Mech_Controller m_Wrapper;
        public ElectronicWarfareOfficerActions(@Mech_Controller wrapper) { m_Wrapper = wrapper; }
        public InputAction @IncreaseMinimapResolution => m_Wrapper.m_ElectronicWarfareOfficer_IncreaseMinimapResolution;
        public InputAction @DecreaseMinimapResolution => m_Wrapper.m_ElectronicWarfareOfficer_DecreaseMinimapResolution;
        public InputAction @PointClick1 => m_Wrapper.m_ElectronicWarfareOfficer_PointClick1;
        public InputAction @PointClick2 => m_Wrapper.m_ElectronicWarfareOfficer_PointClick2;
        public InputAction @RadarSwitchPower => m_Wrapper.m_ElectronicWarfareOfficer_RadarSwitchPower;
        public InputAction @TerrainMapSwitch => m_Wrapper.m_ElectronicWarfareOfficer_TerrainMapSwitch;
        public InputAction @IncreaseSweepSpeed => m_Wrapper.m_ElectronicWarfareOfficer_IncreaseSweepSpeed;
        public InputAction @DecreaseSweepSpeed => m_Wrapper.m_ElectronicWarfareOfficer_DecreaseSweepSpeed;
        public InputAction @ToggleSectorSweep => m_Wrapper.m_ElectronicWarfareOfficer_ToggleSectorSweep;
        public InputAction @IncreaseSectorSweep => m_Wrapper.m_ElectronicWarfareOfficer_IncreaseSectorSweep;
        public InputAction @DecreaseSectorSweep => m_Wrapper.m_ElectronicWarfareOfficer_DecreaseSectorSweep;
        public InputAction @RotateSectorSweepForward => m_Wrapper.m_ElectronicWarfareOfficer_RotateSectorSweepForward;
        public InputAction @RotateSectorSweepBackward => m_Wrapper.m_ElectronicWarfareOfficer_RotateSectorSweepBackward;
        public InputAction @JammTarget => m_Wrapper.m_ElectronicWarfareOfficer_JammTarget;
        public InputActionMap Get() { return m_Wrapper.m_ElectronicWarfareOfficer; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ElectronicWarfareOfficerActions set) { return set.Get(); }
        public void SetCallbacks(IElectronicWarfareOfficerActions instance)
        {
            if (m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface != null)
            {
                @IncreaseMinimapResolution.started -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnIncreaseMinimapResolution;
                @IncreaseMinimapResolution.performed -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnIncreaseMinimapResolution;
                @IncreaseMinimapResolution.canceled -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnIncreaseMinimapResolution;
                @DecreaseMinimapResolution.started -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnDecreaseMinimapResolution;
                @DecreaseMinimapResolution.performed -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnDecreaseMinimapResolution;
                @DecreaseMinimapResolution.canceled -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnDecreaseMinimapResolution;
                @PointClick1.started -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnPointClick1;
                @PointClick1.performed -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnPointClick1;
                @PointClick1.canceled -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnPointClick1;
                @PointClick2.started -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnPointClick2;
                @PointClick2.performed -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnPointClick2;
                @PointClick2.canceled -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnPointClick2;
                @RadarSwitchPower.started -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnRadarSwitchPower;
                @RadarSwitchPower.performed -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnRadarSwitchPower;
                @RadarSwitchPower.canceled -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnRadarSwitchPower;
                @TerrainMapSwitch.started -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnTerrainMapSwitch;
                @TerrainMapSwitch.performed -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnTerrainMapSwitch;
                @TerrainMapSwitch.canceled -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnTerrainMapSwitch;
                @IncreaseSweepSpeed.started -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnIncreaseSweepSpeed;
                @IncreaseSweepSpeed.performed -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnIncreaseSweepSpeed;
                @IncreaseSweepSpeed.canceled -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnIncreaseSweepSpeed;
                @DecreaseSweepSpeed.started -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnDecreaseSweepSpeed;
                @DecreaseSweepSpeed.performed -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnDecreaseSweepSpeed;
                @DecreaseSweepSpeed.canceled -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnDecreaseSweepSpeed;
                @ToggleSectorSweep.started -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnToggleSectorSweep;
                @ToggleSectorSweep.performed -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnToggleSectorSweep;
                @ToggleSectorSweep.canceled -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnToggleSectorSweep;
                @IncreaseSectorSweep.started -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnIncreaseSectorSweep;
                @IncreaseSectorSweep.performed -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnIncreaseSectorSweep;
                @IncreaseSectorSweep.canceled -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnIncreaseSectorSweep;
                @DecreaseSectorSweep.started -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnDecreaseSectorSweep;
                @DecreaseSectorSweep.performed -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnDecreaseSectorSweep;
                @DecreaseSectorSweep.canceled -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnDecreaseSectorSweep;
                @RotateSectorSweepForward.started -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnRotateSectorSweepForward;
                @RotateSectorSweepForward.performed -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnRotateSectorSweepForward;
                @RotateSectorSweepForward.canceled -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnRotateSectorSweepForward;
                @RotateSectorSweepBackward.started -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnRotateSectorSweepBackward;
                @RotateSectorSweepBackward.performed -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnRotateSectorSweepBackward;
                @RotateSectorSweepBackward.canceled -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnRotateSectorSweepBackward;
                @JammTarget.started -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnJammTarget;
                @JammTarget.performed -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnJammTarget;
                @JammTarget.canceled -= m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface.OnJammTarget;
            }
            m_Wrapper.m_ElectronicWarfareOfficerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @IncreaseMinimapResolution.started += instance.OnIncreaseMinimapResolution;
                @IncreaseMinimapResolution.performed += instance.OnIncreaseMinimapResolution;
                @IncreaseMinimapResolution.canceled += instance.OnIncreaseMinimapResolution;
                @DecreaseMinimapResolution.started += instance.OnDecreaseMinimapResolution;
                @DecreaseMinimapResolution.performed += instance.OnDecreaseMinimapResolution;
                @DecreaseMinimapResolution.canceled += instance.OnDecreaseMinimapResolution;
                @PointClick1.started += instance.OnPointClick1;
                @PointClick1.performed += instance.OnPointClick1;
                @PointClick1.canceled += instance.OnPointClick1;
                @PointClick2.started += instance.OnPointClick2;
                @PointClick2.performed += instance.OnPointClick2;
                @PointClick2.canceled += instance.OnPointClick2;
                @RadarSwitchPower.started += instance.OnRadarSwitchPower;
                @RadarSwitchPower.performed += instance.OnRadarSwitchPower;
                @RadarSwitchPower.canceled += instance.OnRadarSwitchPower;
                @TerrainMapSwitch.started += instance.OnTerrainMapSwitch;
                @TerrainMapSwitch.performed += instance.OnTerrainMapSwitch;
                @TerrainMapSwitch.canceled += instance.OnTerrainMapSwitch;
                @IncreaseSweepSpeed.started += instance.OnIncreaseSweepSpeed;
                @IncreaseSweepSpeed.performed += instance.OnIncreaseSweepSpeed;
                @IncreaseSweepSpeed.canceled += instance.OnIncreaseSweepSpeed;
                @DecreaseSweepSpeed.started += instance.OnDecreaseSweepSpeed;
                @DecreaseSweepSpeed.performed += instance.OnDecreaseSweepSpeed;
                @DecreaseSweepSpeed.canceled += instance.OnDecreaseSweepSpeed;
                @ToggleSectorSweep.started += instance.OnToggleSectorSweep;
                @ToggleSectorSweep.performed += instance.OnToggleSectorSweep;
                @ToggleSectorSweep.canceled += instance.OnToggleSectorSweep;
                @IncreaseSectorSweep.started += instance.OnIncreaseSectorSweep;
                @IncreaseSectorSweep.performed += instance.OnIncreaseSectorSweep;
                @IncreaseSectorSweep.canceled += instance.OnIncreaseSectorSweep;
                @DecreaseSectorSweep.started += instance.OnDecreaseSectorSweep;
                @DecreaseSectorSweep.performed += instance.OnDecreaseSectorSweep;
                @DecreaseSectorSweep.canceled += instance.OnDecreaseSectorSweep;
                @RotateSectorSweepForward.started += instance.OnRotateSectorSweepForward;
                @RotateSectorSweepForward.performed += instance.OnRotateSectorSweepForward;
                @RotateSectorSweepForward.canceled += instance.OnRotateSectorSweepForward;
                @RotateSectorSweepBackward.started += instance.OnRotateSectorSweepBackward;
                @RotateSectorSweepBackward.performed += instance.OnRotateSectorSweepBackward;
                @RotateSectorSweepBackward.canceled += instance.OnRotateSectorSweepBackward;
                @JammTarget.started += instance.OnJammTarget;
                @JammTarget.performed += instance.OnJammTarget;
                @JammTarget.canceled += instance.OnJammTarget;
            }
        }
    }
    public ElectronicWarfareOfficerActions @ElectronicWarfareOfficer => new ElectronicWarfareOfficerActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard&Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    private int m_XboxControllerSchemeIndex = -1;
    public InputControlScheme XboxControllerScheme
    {
        get
        {
            if (m_XboxControllerSchemeIndex == -1) m_XboxControllerSchemeIndex = asset.FindControlSchemeIndex("XboxController");
            return asset.controlSchemes[m_XboxControllerSchemeIndex];
        }
    }
    public interface IMechPilotActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnFire1(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnFire2(InputAction.CallbackContext context);
        void OnChangeWeapon(InputAction.CallbackContext context);
    }
    public interface IElectronicWarfareOfficerActions
    {
        void OnIncreaseMinimapResolution(InputAction.CallbackContext context);
        void OnDecreaseMinimapResolution(InputAction.CallbackContext context);
        void OnPointClick1(InputAction.CallbackContext context);
        void OnPointClick2(InputAction.CallbackContext context);
        void OnRadarSwitchPower(InputAction.CallbackContext context);
        void OnTerrainMapSwitch(InputAction.CallbackContext context);
        void OnIncreaseSweepSpeed(InputAction.CallbackContext context);
        void OnDecreaseSweepSpeed(InputAction.CallbackContext context);
        void OnToggleSectorSweep(InputAction.CallbackContext context);
        void OnIncreaseSectorSweep(InputAction.CallbackContext context);
        void OnDecreaseSectorSweep(InputAction.CallbackContext context);
        void OnRotateSectorSweepForward(InputAction.CallbackContext context);
        void OnRotateSectorSweepBackward(InputAction.CallbackContext context);
        void OnJammTarget(InputAction.CallbackContext context);
    }
}
